matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"
    - language: c
        sudo : false # only for faster builds
        compiler:
            -clang
            -gcc
        script:
            -gcc-o test main.c
            -./test
